name: Prison
version: ${project.version}
main: prison.prison.PrisonMain
authors: [Simon_Xz]
description: GnomeMCs Custom Prison Plugin
website: http://gnomemc.net

commands:
  help:
    description:
    usage:
    permission:

