name: Prison
version: 1.0-SNAPSHOT
main: prison.prison.PrisonMain
authors: [Simon_Xz]
description: GnomeMCs Custom Prison Plugin
website: http://gnomemc.net

commands:
  help:
    description: Shows the help page for the plugin
    usage: /help
    permission: prison.help
    permission-message: I'm sorry but you dont have prison.help

